# Настройки сайта
title: "Никита Шишкин"
email: n-i-k-i-t@yandex.ru
url: https://github.com/unsstrennen
description: "Tech Lead / IT Manager, моделирование транспортных систем, разработка ПО, документация, IT / Проектный менеджмент"
keywords: "Сайт,Разработка,Разработчик,IT,Программирование,Проектный менеджмент"
skills: "Tech Lead / IT Manager - Python / DevOps / GIS - Управление проектами"
meta_author: "Шишкин Никита"

# Google webmaster tools
google_verify: WlV4XRDBrqs5SIAbt5h_Kbcxrv6h5ONCtB6yr_5-LiE

# Bing Verification
bing_verify:

# Yandex webmaster tools
yandex_verify: e25ae251c6b88817

# Contact form:
contact: static

# If you use disqus you need disqus shortname
disqus_shortname: myshortname

# Цвета
color:
  primary: 5ecbd1 #80B3FF
  primary-rgb: "94,203,209"
  secondary: 2e5375 #FD6E8A
  secondary-dark: 233140 #A2122F

# Подвал сайта
footer:
  copyright: UnSstrennen
  location: "Где меня найти?"
  social: "Я в соцсетях"
  credits: "Самозанятый, НПД"

# Навыки
skill-bars:
  - title: Python
    percent: 95
  - title: Linux
    percent: 90
  - title: Chat bots
    percent: 95
  - title: Data scrapping
    percent: 80
  - title: HTML
    percent: 80
  - title: CSS
    percent: 45
  - title: JS
    percent: 80
  - title: SQL
    percent: 80
  - title: PHP
    percent: 60
  - title: Scrum
    percent: 65
  - title: Docs (RU)
    percent: 95
  - title: Docs (EN)
    percent: 90
  - title: Unit-testing
    percent: 90
  - title: C/C++
    percent: 70
  - title: Arduino
    percent: 95
  - title: AVR
    percent: 70

# Соцсети
social:
  - title: telegram
    url: https://t.me/unsstrennen
  - title: stack-overflow
    url: https://stackoverflow.com/users/9231573/Nikita-Shishkin
  - title: github
    url: https://github.com/UnSstrennen
  - title: habr
    url: https://habr.com/ru/users/unsstrennen/

# Адрес
address:
  - line: "Москва, РФ / Куала-Лумпур, Малайзия"
  - line: "Готов к очным встречам в своём городе!"

# Credits
credits: "ИП Шишкин Никита Сергеевич<br>ОГРНИП 323774600009751"

# Настройки сборки
markdown: kramdown
permalink: pretty

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
