langs:
  ru:
    title: "Никита Шишкин"
    email: "n-i-k-i-t@yandex.ru"
    url: "https://github.com/unsstrennen"
    description: "Tech Lead / IT Manager, моделирование транспортных систем, разработка ПО, документация, IT / Проектный менеджмент"
    keywords: "Сайт,Разработка,Разработчик,IT,Программирование,Проектный менеджмент"
    meta_author: "Шишкин Никита"
    skills: "Tech Lead / IT Manager"

    footer:
      copyright: UnSstrennen
      location: "Где меня найти?"
      social: "Я в соцсетях"
      credits: "Индивидуальный предприниматель"

    address:
      - line: "Москва, РФ / Куала-Лумпур, Малайзия"
      - line: "Готов к очным встречам в своём городе!"

    credits: "ИП Шишкин Никита Сергеевич<br>ОГРНИП 323774600009751"

  en:
    title: "Nikita Shishkin"
    email: "n-i-k-i-t@yandex.ru"
    url: "https://github.com/unsstrennen"
    description: "Tech Lead / IT Manager, transport systems modeling, software development, documentation, IT / Project management"
    keywords: "Website,Development,Developer,IT,Programming,Project management"
    meta_author: "Nikita Shishkin"
    skills: "Tech Lead / IT Manager"

    footer:
      copyright: UnSstrennen
      location: "Where to find me?"
      social: "Follow me on social media"
      credits: "Self-employed entrepreneur"

    address:
      - line: "Moscow, Russia / Kuala Lumpur, Malaysia"
      - line: "Available for in-person meetings in my city!"

    credits: "IP Shishkin Nikita Sergeevich<br>OGRNIP 323774600009751"

google_verify: WlV4XRDBrqs5SIAbt5h_Kbcxrv6h5ONCtB6yr_5-LiE
bing_verify:
yandex_verify: e25ae251c6b88817

contact: static
disqus_shortname: myshortname

color:
  primary: 5ecbd1
  primary-rgb: "94,203,209"
  secondary: 2e5375
  secondary-dark: 233140

skill-bars:
  - title: IT Strategy
    percent: 95
  - title: Project Mgmt
    percent: 90
  - title: Agile / Scrum
    percent: 90
  - title: DevOps / CI/CD
    percent: 85
  - title: Sys Architecture
    percent: 85
  - title: Fullstack Mgmt
    percent: 80
  - title: Python 3
    percent: 100
  - title: PostgreSQL
    percent: 90
  - title: High-Load
    percent: 80
  - title: Data Analysis
    percent: 75
  - title: Tech Docs
    percent: 95
  - title: Risk & Quality
    percent: 80
  - title: Cloud / Network
    percent: 75
  - title: Team Leadership
    percent: 90
  - title: GIS / Maps
    percent: 70
  - title: IoT Oversight
    percent: 65

social:
  - title: telegram
    url: https://t.me/unsstrennen
  - title: stack-overflow
    url: https://stackoverflow.com/users/9231573/Nikita-Shishkin
  - title: github
    url: https://github.com/UnSstrennen
  - title: linkedin
    url: https://www.linkedin.com/in/nikita-shishkin-07a8a6128

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
