langs:
  ru:
    title: "Никита Шишкин"
    email: "n-i-k-i-t@yandex.ru"
    url: "https://github.com/unsstrennen"
    description: "Tech Lead / IT Manager, моделирование транспортных систем, разработка ПО, документация, IT / Проектный менеджмент"
    keywords: "Сайт,Разработка,Разработчик,IT,Программирование,Проектный менеджмент"
    meta_author: "Шишкин Никита"
    skills: "Tech Lead / IT Manager"

    footer:
      copyright: UnSstrennen
      location: "Где меня найти?"
      social: "Я в соцсетях"
      credits: "Индивидуальный предприниматель"

    address:
      - line: "Москва, РФ / Куала-Лумпур, Малайзия"
      - line: "Готов к очным встречам в своём городе!"

    credits: "ИП Шишкин Никита Сергеевич<br>ОГРНИП 323774600009751"

  en:
    title: "Nikita Shishkin"
    email: "n-i-k-i-t@yandex.ru"
    url: "https://github.com/unsstrennen"
    description: "Tech Lead / IT Manager, transport systems modeling, software development, documentation, IT / Project management"
    keywords: "Website,Development,Developer,IT,Programming,Project management"
    meta_author: "Nikita Shishkin"
    skills: "Tech Lead / IT Manager"

    footer:
      copyright: UnSstrennen
      location: "Where to find me?"
      social: "Follow me on social media"
      credits: "Self-employed entrepreneur"

    address:
      - line: "Moscow, Russia / Kuala Lumpur, Malaysia"
      - line: "Available for in-person meetings in my city!"

    credits: "Sole proprietor Nikita Sergeevich Shishkin<br>OGRNIP 323774600009751"

google_verify: WlV4XRDBrqs5SIAbt5h_Kbcxrv6h5ONCtB6yr_5-LiE
bing_verify:
yandex_verify: e25ae251c6b88817

contact: static
disqus_shortname: myshortname

color:
  primary: 5ecbd1
  primary-rgb: "94,203,209"
  secondary: 2e5375
  secondary-dark: 233140

skill-bars:
  - title: Python
    percent: 95
  - title: Linux
    percent: 90
  - title: Chat bots
    percent: 95
  - title: Data scrapping
    percent: 80
  - title: HTML
    percent: 80
  - title: CSS
    percent: 45
  - title: JS
    percent: 80
  - title: SQL
    percent: 80
  - title: PHP
    percent: 60
  - title: Scrum
    percent: 65
  - title: Docs
    percent: 95
  - title: Unit-testing
    percent: 90
  - title: C/C++
    percent: 70
  - title: Arduino
    percent: 95
  - title: AVR
    percent: 70

social:
  - title: telegram
    url: https://t.me/unsstrennen
  - title: stack-overflow
    url: https://stackoverflow.com/users/9231573/Nikita-Shishkin
  - title: github
    url: https://github.com/UnSstrennen
  - title: habr
    url: https://habr.com/ru/users/unsstrennen/

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
